language: java
jdk:
 - openjdk6
 - Oracle JDK 7
script:  mvn clean install
matrix:
  allow_failures: 
    - Oracle JDK 7
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#OpenMRS"
    template:
      - "[%{repository}] [%{commit}] [%{author}] %{message} - %{build_url}"
